config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'user/show'
  get 'user/index'
  resources :users
  resources :tweets
  resources :tags
  resources :words
  post 'words/:id', to: 'words#save_meanings'
  # delete 'sessions/destroy'
  # get 'sessions/new'
  # post 'sessions/new'
  # post 'sessions/create'
  resources :sessions
  root 'application#index'

  get 'login', to: 'logins#new'
  get 'login/create', to: 'logins#create', as: :create_login
  post 'users/auth'
  post 'users/signout'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get '/', to: 'sync#index'
      get 'fetch', to: 'sync#fetch'
      post 'post', to: 'sync#post'
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  has_one_attached :picture
  has_many :meanings
  has_many :word_tags
  has_many :tags, through: :word_tags

  accepts_nested_attributes_for :word_tags, allow_destroy: true, reject_if: proc { |att| att['tag_id'].blank? }

  def to_s
    farsiAlphabet = Alphabet.find_by code: 'fa'
    farsiLanguage = Language.find_by code: 'fa'
    meaning = meanings.find_by language: farsiLanguage, alphabet: farsiAlphabet
    meaning ||= meanings.where.not(text: '').first || ''
  end

  def update_meanings(params)
    Alphabet.all.map do |alphabet|
      Language.all.map do |language|
        if text = params["Language#{language.code}Alphabet#{alphabet.code}"]
          meanings.find_or_create_by(alphabet: alphabet, language: language).update_attributes text: text
        end
      end
    end
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:show, :edit, :update, :destroy, :save_meanings]

  # GET /words
  # GET /words.json
  def index
    @words = Word.all.includes(:meanings)
  end

  # GET /words/1
  # GET /words/1.json
  def show
  end

  # POST /words/1
  def save_meanings
    respond_to do |format|
      if @word.update_meanings(params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /words/new
  def new
    @word = Word.new
    @word.word_tags.build
  end

  # GET /words/1/edit
  def edit
    @word.word_tags.new
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(word_params)

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render :show, status: :created, location: @word }
      else
        format.html { render :new }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /words/1
  # PATCH/PUT /words/1.json
  def update
    respond_to do |format|
      if @word.update(word_params)
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { render :show, status: :ok, location: @word }
      else
        format.html { render :edit }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word.destroy
    respond_to do |format|
      format.html { redirect_to words_url, notice: 'Word was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word
      @word = Word.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_params
      params.fetch(:word, {}).permit(:picture, word_tags_attributes: [:id, :tag_id, :_destroy])
      # params.require(:word).permit(:picture, :word_tags)
    end
end

app/views/words/_form.html.erb
<%= form_with(model: word, local: true) do |form| %>
  <% if word.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word.errors.count, "error") %> prohibited this word from being saved:</h2>

      <ul>
      <% word.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <h1>
    <%= form.object %>
  </h1>
  <%= form.file_field :picture %><br>
  <%= form.fields_for :word_tags do |wt| %>
      <div class="field">
        <%= wt.label :tag_id %>
        <%= wt.select :tag_id, Tag.all.collect{|p| [p.text, p.id]}, include_blank: true %>

    <% if wt.object.persisted? %>
      <%= wt.check_box :_destroy %>
      <%= wt.label :_destroy, "Destroy" %>
    <% end %>
    </div>
  <% end %>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/words/edit.html.erb
<h1>Editing Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Show', @word %> |
<%= link_to 'Back', words_path %>

app/views/words/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Words</h1>

<table>
  <thead>
    <tr>
      <th>Word</th>
      <%= Language.pluck(:flag).map { |flag| "<th>#{flag}</th>"  }.join.html_safe %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @words.each do |word| %>
      <tr>
        <td><%= image_tag(word.picture.variant(resize: "200")) if word.picture.attached? %></td>
        <%= Language.all.map { |lang|
          "<td>" + word.meanings.where(language: lang).map { |meaning| meaning.text.empty? ? '' :  "<span class='#{meaning.alphabet.code}'>#{meaning}</span><br />" }.join + "</td>"
        }.join.html_safe %>
        <td><%= link_to 'Show', word %></td>
        <td><%= link_to 'Edit', edit_word_path(word) %></td>
        <td><%= link_to 'Destroy', word, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Word', new_word_path, class: 'button' %>

<p>
  <%= link_to 'https://translate.google.com/' %>
  <br />
  <%= link_to 'https://www.google.com/inputtools/try/' %>
</p>

app/views/words/new.html.erb
<h1>New Word</h1>

<%= render 'form', word: @word %>

<%= link_to 'Back', words_path %>

app/views/words/show.html.erb
<p id="notice"><%= notice %></p>
<%= image_tag(@word.picture.variant(resize: "300x300")) if @word.picture.attached? %>
<br />
<strong>Tags:</strong> <%= @word.tags.uniq.map{|tag| link_to tag, tag}.join(' - ').html_safe %>
<%= link_to 'Edit', edit_word_path(@word), class: 'button right' %>
<%= link_to 'Back', words_path, class: 'button right' %>
<%= form_with(model: @word, local: true, method: 'post') do |form| %>
  <table class="table">
    <thead>
      <th>

      </th>
      <%= Language.all.map { |lang| "<th>#{lang.flag} - #{lang.name} - #{lang.code}</th>"  }.join.html_safe %>
    </thead>
    <% Alphabet.all.map do |alphabet| %>
      <tr>
        <td>
          <%= "#{alphabet.flag} - #{alphabet.name} - #{alphabet.code}" %>
        </td>
        <% Language.all.map do |lang|
          meaning = @word.meanings.where(language: lang, alphabet: alphabet).first&.text
        %>
          <td>
            <input
              class='meaning'
              data-language='<%=lang.code%>'
              data-alphabet='<%=alphabet.code%>'
              name="Language<%=lang.code%>Alphabet<%=alphabet.code%>"
              placeholder="<%="#{alphabet.flag} - #{alphabet.name} - #{alphabet.code}"%>"
              value="<%=meaning%>"
            />
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <div class="actions">
    <%= form.submit %>
    <%= button_tag "Reset", type: :reset %>
  </div>
<% end %>